[project]
name = "transcriber_tool"
version = "0.1.0"
description = "音声ファイルをテキストに変換するCLIツール"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper",
    "click",
    "ctranslate2>=4.0,<5",
    "huggingface-hub>=0.13",
    "tokenizers>=0.13,<1",
    "onnxruntime>=1.14,<2",
    "av>=11",
    "tqdm",
    "requests",
]

[project.scripts]
transcriber_tool = "transcriber_tool.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
